apiVersion: v1
kind: Service
metadata:
  name: {{ include "settle-server.fullname" . }}
  labels:
    {{- include "settle-server.labels" . | nindent 4 }}
    tags.datadoghq.com/env: {{ .Values.env }}
    tags.datadoghq.com/service: {{ include "settle-server.fullname" . }}
    tags.datadoghq.com/version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "settle-server.selectorLabels" . | nindent 4 }}
