{{- if .Values.sidekiq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: {{ .Values.sidekiq.replicaCount }}
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        command: [ "bundle" ]
        args:
          - "exec"
          - "sidekiq"
          - "-C"
          - "config/sidekiq/common.yml"
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_ADDRESS
            value: redis:6379
        envFrom:
           - configMapRef:
               name: settle-server-config
{{- end }}
