{{- if .Values.sidekiq.enabled }}
{{- range $key, $value := $.Values.sidekiq.workers }}
{{- with $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}
spec:
  replicas: {{ $value.replicaCount }}
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        command: {{ $value.command }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configMap }}
{{- end }}
{{- end }}
{{- end }}