{{- if .Values.sidekiq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: {{ .Values.sidekiq.replicaCount }}
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        command: ["bundle", "exec", "sidekiq"]
        envFrom:
          - configMapRef:
              name: {{ .Values.sidekiq.configMap }}
{{- end }}