# Default values for this chart.

nameOverride: ""
fullnameOverride: ""

env: "stg"

# Minimum number of pods to deploy
replicaCount: 1

# Specify a ConfigMap and/or Secret resource that has been created separately
configMap: ""
secretMap: ""

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  # annotations: {}
  # name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  # className: ""
  # annotations: {}
  # hosts:
  #   - host: chart-example.local
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

sidekiq:
  enabled: false
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # workers:
  #   worker:
  #     replicaCount: 1
  #     command: bundle
  #     args:
  #       - "exec"
  #       - "sidekiq"
  #       - "-C"
  #       - "config/sidekiq/common.yml"
  #   critical-worker:
  #     replicaCount: 1
  #     command: bundle
  #     args:
  #       - "exec"
  #       - "sidekiq"
  #       - "-C"
  #       - "config/sidekiq/production/critical.yml"

# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes
# startupProbe: {}
  # httpGet:
  #   path: /admins/sign_in
  #   port: 8080
  # initialDelaySeconds: 45
  # periodSeconds: 10
  # failureThreshold: 10

# https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/
lifecycle: {}
  # postStart:
  #   exec:
  #     command:
  #       - "/bin/sh"
  #       - "-c"
  #       - >
  #         bin/rails db:migrate && if ! bundle exec rails runner 'exit(Admin.any?)'; then
  #           bundle exec rails db:seed;
  #         fi

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 20
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

imagePullSecrets: []

initContainers: []

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
