{{- if .Values.sidekiq.enabled }}
{{- range $key, $value := $.Values.sidekiq.workers }}
{{- with $ }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-{{ $key }}
spec:
  replicas: {{ $value.replicaCount }}
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["{{ $value.command }}"]
          args:
            {{- range $value.args }}
            - "{{ . }}"
            {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Values.configMap }}
          - secretRef:
              name: {{ .Values.secretMap }}
          resources:
            {{- toYaml .Values.sidekiq.resources | nindent 12 }}
      {{- with .Values.sidekiq.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sidekiq.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sidekiq.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}